subugoe/tido

- tests/cypress/e2e/variants.cy.js
In this PR I add a few tests regarding:
- highlighted text selection
- showing witnesses details
- variant items list
> Tests: highlighted text selection + witnesses details + variants list

- src/components/TreeView.vue
> fix: update caret position in tree

- src/i18n/en/index.js
- tests/cypress/e2e/metadata.cy.js
> feat: change language display label

- src/App.tsx
- src/components/PanelsWrapper.tsx
- src/store/ConfigStore.tsx
- src/types.d.ts
With Zustand we have a global state management solution. Since we are wrapping the whole app with the ConfigContext, it is more reasonable to use the Zustand store for this.
> Config store

- src/components/metadata/ManifestMetadata.vue
- src/components/metadata/MetadataItem.vue
- src/components/metadata/MetadataValue.vue
> fix: nested metadata display

- src/components/ContentView.vue
- src/css/_highlighting.scss
- src/stores/annotations.ts
- src/utils/annotations.js
annotation icons in text have now primary color and rendered as svg elements and not as content prop
> Fix annotation icons

- src/components/annotations/AnnotationsView.vue
click on target in text panel, annotation item should scroll into view in annotation panel
> feat: scroll to annotation item when clicked in text

- src/components/annotations/AnnotationsList.vue
- src/stores/annotations.ts
- src/stores/config.ts
> feat: add an option in config to have no icons for annotations

- .github/workflows/ci.yml
- src/components/annotations/variants/VariantItem.vue
- src/components/annotations/variants/VariantsTopBar.vue
- src/stores/annotations.ts
- src/types.d.ts
- src/utils/annotations.js
in variant items, idnoAlt is displayed, on hover title is displayed
> feat: display siglums in variant items and show witness titles on hover

- .github/workflows/ci.yml
- examples/e2e.html
- src/components/TopBar.tsx
- tests/cypress/e2e/app.cy.js
- tests/cypress/e2e/config.cy.js
Introducing config testing. There is a new example file "e2e.html" which dynamically creates a config for the app. It takes query params appended to the URL and converts them to config props. The params can be added at .visit call of a Cypress test. We are starting off with a test for primary color.
> Config e2e

- examples/config/4w.json
- package-lock.json
- package.json
- public/translations/de.json
- public/translations/en.json
- src/components/Modal.tsx
- src/components/PanelsWrapper.tsx
- src/components/TopBar.tsx
- src/components/panel/AddPanel.tsx
- src/components/panel/Panel.tsx
- src/components/tree/tree-modal/TreeSelectionModalContent.tsx
- src/components/ui/dialog.tsx
- src/components/ui/popover.tsx
- tailwind.config.js
closes #603
- additionally adds resizing of panels
- introduces dialog ui component
- improves tree selection modal content
> Ghost panel

- examples/config/4w-local.json
- examples/config/4w.json
- examples/config/default.json
- src/components/panel/TextViewsToggle.tsx
- src/components/panel/views/PanelCentralContent.tsx
- src/contexts/PanelContext.tsx
- src/types.d.ts
- src/utils/config/config.ts
- src/utils/config/default-config.ts
- tests/cypress/e2e/config.cy.js
- adds  global "defaultView" config option, so all new opened panels will open with this view
- closes #604
> Default view config

- src/components/tree/GlobalTree.tsx
- src/components/tree/Tree.tsx
- src/components/tree/TreeNode.tsx
- src/components/tree/tree-modal/GlobalTreeSelectionModalContent.tsx
- src/components/tree/tree-modal/TreeSelectionModalContent.tsx
> Tree fixes

- examples/config/4w-local.json
- examples/config/4w.json
- examples/config/default.json
- src/components/panel/ContentTypesToggle.tsx
- src/components/tree/GlobalTree.tsx
The PR aims to close the following issues
Closes #630 
Closes #632
> Add translations for Content types toggle labels

- examples/config/default.json
- src/components/header/AddNewPanel.tsx
- src/components/header/TopBar.tsx
- src/types.d.ts
- src/utils/config/config.ts
- src/utils/config/default-config.ts
- tests/cypress/e2e/app.cy.js
- tests/cypress/e2e/config.cy.js
allowNewCollections controls whether the new collection input is shown or not, if false the add new panel button will trigger the tree dialog directly
> Config dynamic collection

- src/components/metadata/CollectionMetadata.tsx
- src/components/metadata/ItemMetadata.tsx
- src/components/metadata/ManifestMetadata.tsx
- src/components/metadata/Metadata.tsx
- src/components/ui/accordion.tsx
>  improve the design of metadata heading on hover

- src/contexts/PanelContext.tsx
- src/store/PanelStore.tsx
> fix: read view index from panelState while rendering Panel

- src/store/DataStore.tsx
- src/utils/tree.ts
> Show the root Nodes of tree which have valid api response

- src/components/panel/ImageRenderer.tsx
> Add loading spinner while image is loading

- src/components/tree/GlobalTree.tsx
- src/components/tree/TreeNode.tsx
- src/components/tree/TreeSelection.tsx
- src/utils/tree.ts
- tests/cypress/e2e/tree.cy.js
> Expand a single tree node initially

- src/components/panel/CollectionTitle.tsx
- src/components/tree/LocalTree.tsx
> Implement local tree

- examples/config/4w-local.json
- src/components/Tido.tsx
- src/components/panel/PanelBody.tsx
- src/components/panel/TextViewsToggle.tsx
- src/components/panel/select-view/DisableSelectView.tsx
- src/components/panel/select-view/SelectTextView.tsx
- src/components/panel/select-view/Views.tsx
- src/contexts/PanelContext.tsx
- src/store/PanelStore.tsx
- src/store/UIStore.tsx
- src/types.d.ts
- src/utils/config/config.ts
- src/utils/config/default-config.ts
- src/utils/panel.ts
- tests/cypress/e2e/config.cy.js
> Add make view configurable

- package-lock.json
- package.json
- public/translations/de.json
- public/translations/en.json
- src/components/panel/Panel.tsx
- src/components/panel/TextRenderer.tsx
- src/components/panel/views/TextView.tsx
- src/components/panel/views/TextViewError.tsx
- src/components/panel/views/TextViewWarning.tsx
- src/components/ui/button.tsx
- src/contexts/PanelContext.tsx
- src/css/style.css
- src/utils/panel-resizer.ts
starting using error bounaries (if concept proves itself, we can expand it to other parts of the app), show warning if any nodes have been removed from the text after sanitizing
closes #710
> feat: add text sanitizing, show warning and error at text view

- src/components/panel/CollectionTitle.tsx
- src/components/panel/ItemLabel.tsx
- src/components/panel/ManifestLabel.tsx
- src/components/panel/Panel.tsx
> feat: resize panel titles based on panel width

- src/components/panel/ImageRenderer.tsx
- src/components/panel/ImageRendererError.tsx
- src/components/panel/views/ImageView.tsx
- src/contexts/PanelContext.tsx
- tests/cypress/e2e/panel.cy.js
> Fix images not loading

- package-lock.json
- package.json
- src/components/Tido.tsx
- src/contexts/PanelContext.tsx
> fix: check the response of annotation collection

- src/components/panel/annotations/WitnessChip.tsx
> Check for witness value in witness chip

- examples/config/ahiqar.json
- public/translations/de.json
- src/components/panel/Panel.tsx
- src/components/panel/TextRenderer.tsx
- src/components/panel/annotations/AlignAnnotationsList.tsx
- src/components/panel/annotations/Annotation.tsx
- src/components/panel/annotations/AnnotationFilters.tsx
- src/components/panel/annotations/AnnotationsHeader.tsx
- src/components/panel/annotations/AnnotationsList.tsx
- src/components/panel/annotations/AnnotationsModeToggle.tsx
- src/components/panel/annotations/AnnotationsView.tsx
- src/contexts/PanelContext.tsx
- src/types.d.ts
- src/utils/config/config.ts
- src/utils/config/default-config.ts
- src/utils/dom.ts
> Implement annotations list
